steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/smart-tangent-248502/gcp-cloudbuild-gce-angular', '.' ]



images:

- 'gcr.io/smart-tangent-248502/gcp-cloudbuild-gce-angular'
